---
output:
  github_document:
    html_preview: false
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## Overview binomial package and Motivation

The package `"binomial"` is an R package that implements functions for calculating probabilities of a Binomial random variable, and related calculations such as the probability distribution, the exptected value, variance, etc. Moreover, the package also gives the summary of Binomial and visualizes the summary.


## Usage
```{r}
library(binomial)

# bin_choose()
bin_choose(5, 4)


# bin_probability()
bin_probability(3, 5, 0.5)


# bin_distribution() and its plotting
data1 <- bin_distribution(5, 0.5)  # the user can plot data1 by plot(data1)
data1


# bin_cumulative() and its plotting 
data2 <- bin_cumulative(5, 0.5)
data2  # the user can plot data2 by plot(data2)


# bin_variable() and its summary
bin1 <- bin_variable(trials = 10, prob = 0.3)
bin1 

binsum1 <- summary(bin1)
binsum1

# bin_mean()
bin_mean(10, 0.3)

# bin_variance()
bin_variable(10, 0.3)

# bin_mode()
bin_mode(10, 0.3)

# bin_skewness()
bin_skewness(10, 0.3)

# bin_kurtosis()
bin_kurtosis(10, 0.3)

```

